import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Tutorcito",
	description: "Generated by create next app",
	category: "Education",
	keywords: [
		"Tutorias",
		"tutores",
		"Tutores universitarios"
	]
};